[workspace]
members = [
    "./crates/javelin",
    "./crates/javelin-codec",
    "./crates/javelin-types",
    "./crates/javelin-core",
    "./crates/javelin-rtmp",
    "./crates/javelin-hls",
]


[profile.release]
opt-level = 3
lto = false # some linking errors with lto = true
