[graph]
targets = [
    "x86_64-unknown-linux-gnu"
]


[sources]
unknown-registry = "deny"
unknown-git = "deny"

[sources.allow-org]
github = [
    "valeth",
]


[advisories]
ignore = [
    "RUSTSEC-2024-0320" # TODO: rewrite config handling and remove yaml-rust
]


[licenses]
private.ignore = true
allow = [
    "MIT",
    "Apache-2.0",
    "BSD-3-Clause",
]

[[licenses.exceptions]]
crate = "unicode-ident"
allow = ["Unicode-DFS-2016"]

[[licenses.exceptions]]
crate = "javelin"
allow = ["GPL-3.0"]

[[licenses.exceptions]]
crate = "javelin-codec"
allow = ["GPL-3.0"]

[[licenses.exceptions]]
crate = "javelin-core"
allow = ["GPL-3.0"]

[[licenses.exceptions]]
crate = "javelin-hls"
allow = ["GPL-3.0"]

[[licenses.exceptions]]
crate = "javelin-rtmp"
allow = ["GPL-3.0"]

[[licenses.exceptions]]
crate = "javelin-srt"
allow = ["GPL-3.0"]

[[licenses.exceptions]]
crate = "javelin-types"
allow = ["GPL-3.0"]


[bans]
multiple-versions = "deny"
wildcards = "deny"
allow-wildcard-paths = true
external-default-features = "allow" # very noisy when set to "warn"
workspace-default-features = "allow"

[[bans.deny]]
name = "openssl"

[[bans.deny]]
name = "bytes"
version = "<1"

[[bans.deny]]
name = "tokio"
version = "<1"


[[bans.deny]]
name = "futures"
version = "<0.3"

[[bans.deny]]
name = "uuid"
version = "<1"

[[bans.skip]]
name = "syn"
version = "<2.0"
reason = "some core crates still depend on syn version 1 (mostly sqlx)"

[[bans.skip]]
name = "sync_wrapper"
version = "=0.1"
# reason = "axum depends on two different versions through tower"

[[bans.skip]]
name = "hashbrown"
version = "=0.14"
reason = "sqlx depends on two different versions"
