[graph]
targets = [
    "x86_64-unknown-linux-gnu"
]


[sources]
unknown-registry = "deny"
unknown-git = "deny"


[advisories]
version = 2
ignore = [
    # # vulnerable h2 crate is only used by http client
    # "RUSTSEC-2024-0003"
]

[licenses]
private.ignore = true

# ring is pulled in by rustls
[[licenses.exceptions]]
name = "ring"
allow = ["ISC", "MIT", "OpenSSL"]

[[licenses.clarify]]
name = "ring"
expression = "ISC AND MIT AND OpenSSL"
license-files = [{ path = "LICENSE", hash = 0xbd0eed23 }]


[bans]
multiple-versions = "deny"
wildcards = "deny"
allow-wildcard-paths = true
external-default-features = "allow" # very noisy when set to "warn"
workspace-default-features = "allow"

[[bans.deny]]
name = "openssl"

[[bans.deny]]
name = "tokio"
version = "<1"

[[bans.deny]]
name = "futures"
version = "<0.3"

[[bans.deny]]
name = "uuid"
version = "<1"

# Some core crates still depend on syn 1 (mostly sqlx)
[[bans.skip]]
name = "syn"
version = "<2.0"
